services:
  - type: web
    name: kitune-bot
    env: python
    plan: free
    buildCommand: ./.render-build.sh
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false

  - type: worker
    name: git-auto-backup
    env: python
    plan: free
    buildCommand: ./.render-build.sh
    startCommand: python auto_push.py
    envVars:
      - key: GIT_REPO_URL
        sync: false
      - key: GIT_EMAIL
        sync: false
      - key: GIT_NAME
        sync: false
