services:
  - type: web
    name: kitune-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
